---
apiVersion: v1
kind: Secret
metadata:
  name: tpa-postgresql-credentials
  labels:
    app: tpa-postgresql
type: Opaque
stringData:
  db.host: "tpa-postgresql"
  db.name: "tpadb"
  db.user: "tpauser"
  db.password: "r3dh8t1!"
  db.admin: "postgres"
  db.adminpassword: "adminr3dh8t1!"
  db.port: "5432"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tpa-postgresql-data
  labels:
    app: tpa-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpa-postgresql
  labels:
    app: tpa-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpa-postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tpa-postgresql
    spec:
      containers:
        - name: postgresql
          image: registry.redhat.io/rhel9/postgresql-16:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: tpa-postgresql-credentials
                  key: db.user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpa-postgresql-credentials
                  key: db.password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: tpa-postgresql-credentials
                  key: db.name
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tpa-postgresql-credentials
                  key: db.adminpassword
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - --live
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /usr/libexec/check-container
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 100m
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: tpa-postgresql-data

---
apiVersion: v1
kind: Service
metadata:
  name: tpa-postgresql
  labels:
    app: tpa-postgresql
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: tpa-postgresql
  type: ClusterIP
